openapi: 3.0.1
info:
  title: SwiftLink
  version: v1
servers:
  - url: https://localhost:5001
paths:
  /api/v1/Link/Shorten:
    post:
      tags:
        - Link
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GenerateShortCodeCommand'
          text/json:
            schema:
              $ref: '#/components/schemas/GenerateShortCodeCommand'
          application/*+json:
            schema:
              $ref: '#/components/schemas/GenerateShortCodeCommand'
      responses:
        '200':
          description: Success
  '/api/{shortCode}':
    get:
      tags:
        - Link
      parameters:
        - name: shortCode
          in: path
          required: true
          schema:
            type: string
        - name: password
          in: query
          schema:
            type: string
      responses:
        '200':
          description: Success
components:
  schemas:
    GenerateShortCodeCommand:
      type: object
      properties:
        url:
          type: string
          nullable: true
        description:
          type: string
          nullable: true
        expirationDate:
          type: string
          format: date-time
          nullable: true
        password:
          type: string
          nullable: true
        token:
          type: string
          format: uuid
      additionalProperties: false